### ISSUE TITLE
Use rem units and `100%` as the root font size

### ISSUE THREAD

**Issue by CallMeMantas** [igoradamenko/awsm.css#76]
http://stackoverflow.com/questions/6803016/css-100-font-size-100-of-what

**Comment by CallMeMantas** [comment]
Sorry, I was writing this issue on my phone and clicked submit by accident. 

Basically, `100%` for the root font size means that the size of the text can be changed by the user if need be. To scale to that size you can use percentages or `rem` units (as I prefer).

**Comment by igoradamenko** [comment]
@CallMeMantas, good idea! 

There is only one moot point because of [fluid typography](https://github.com/igoradamenko/awsm.css/blob/master/dev/scss/awsm.scss#L20). So if we start to use rems for font size, we should to move from px to rems for page width too (we can multiply only number & dimension and divide only dimension to number).

But if we use rems for page width, it becomes dynamic. `width: 20rem` & users font size 20px == `width: 400px`, not 320.

So, should we change page size if use change initial font size? On the one hand, it's OK. If user changes font size, it's OK try to save number of symbols in the row. On the other hand, it's bad behavior. User don't want to change scale of page. If so he can change it manually.

I've created #78 with example of moving from px to rem, but I'm not sure that it's good idea to change page width. This is a question about a11y and we should discuss it before merging.

**Comment by igoradamenko** [comment]
So, I've thought about your idea a little bit. And I've decided that it's OK to change `max-width` if user changes initial font size and I've merged #78. It's not breaking adaptivity, 'cause we change `max-` and `min-width`, not a `width`.

Thank you for your idea. Feel free to create more issues & pull requests if you have another ideas :koala:
